### PR TITLE
Client prototype

### PR DESCRIPTION
**Pull request by alexbocharov**
Ready for further redesign.

@davidfowl @DamianEdwards

### CODE REVIEW

**Comment by davidfowl** [comment]
What is this?

**Comment by alexbocharov** [comment]
I ported the client functionality 2.2.0. This is the initial stage of work ([Issue #3](https://github.com/aspnet/SignalR-Client-Net/issues/3) ).

**Comment by moozzyk** [comment]
@alexbocharov - unfortunately I don't think we just want to copy the code of the old client like that. There are some quite fundamental changes we would like to made and at the same time we would like to follow patterns we use in AspNetCore.

**Comment by alexbocharov** [comment]
@moozzyk - You can tell me more detail about the changes?

**Comment by moozzyk** [comment]
I created a preliminary list here - https://github.com/aspnet/SignalR-Client-Net/issues/5
More items will probably have to be added to this list. Some of the ideas are taken from the https://github.com/aspnet/SignalR-Client-Cpp I wrote a while ago.

**Comment by alexbocharov** [comment]
> I created a preliminary list here - #5
>  More items will probably have to be added to this list. Some of the ideas are taken from the https://github.com/aspnet/SignalR-Client-Cpp I wrote a while ago. 

I'm all for these changes. I'm going to move on to #5 on the next step. The question is in what to be engaged in refactoring of the ported client or to do everything from a blank sheet.

**Comment by Eilon** [comment]
@alexbocharov we really don't know exactly what we want to do here, that's the problem. The list that @moozzyk started is just a start of a list of some things we want to change, but we don't even know which of those are the most important, and which things are missing from the list.

We appreciate all your effort but at this time I feel it's just too early to do anything meaningful here.

**Comment by alexbocharov** [comment]
@moozzyk @Eilon
I propose to introduce a list of planned activities of the client development (like #5). This will allow all moving in the same direction.

**Comment by moozzyk** [comment]
@alexbocharov - As @Eilon said. I don't think we are ready to move forward with this at this point.

**Comment by Eilon** [comment]
@alexbocharov the main blocker right now is that our team simply doesn't have the time to dedicate to planning this. We are very busy with other critical items.

**Comment by ZoolWay** [comment]
Hello!

With the release of .NET Core and ASP.NET Core and the fact that we already started into Q3 2016, how are plan now? SignalR is one of the Post-1.0 release features of ASP.NET 1.0.

**Comment by Eilon** [comment]
@ZoolWay yup, we just had a kick-off meeting yesterday to go over some of the plans for ASP.NET Core SignalR. We'll have @DamianEdwards post some info about the plans, timeline, etc.

**Comment by davidfowl** [comment]
Work has started on the new signalr client in aspnet/SignalR

**Pull request closed without merging**
